# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 18:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20170131_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispositivo',
            name='nombre',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
