# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 18:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20170131_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispositivo',
            name='descripcion',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='dispositivo',
            name='nombre',
            field=models.CharField(max_length=128),
        ),
    ]
