# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 18:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20170131_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horario',
            name='descripcion',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
