# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 12:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20170131_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='dispositivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personas', to='core.Dispositivo'),
        ),
    ]
