# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-03 13:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20170202_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='core.Persona'),
        ),
    ]
