# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 09:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_segmentohorario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horario',
            name='final',
        ),
        migrations.RemoveField(
            model_name='horario',
            name='inicio',
        ),
    ]
