# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 10:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_dispositivo_actualizacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=128)),
                ('valor', models.CharField(max_length=128)),
                ('tipo', models.IntegerField(choices=[(1, 'Numero'), (2, 'Cadena'), (3, 'JSON'), (4, 'Booleano')])),
            ],
        ),
    ]
