# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 12:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_configuracion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feriado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('motivo', models.CharField(max_length=256)),
                ('recurrente', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Justificacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('aval', models.TextField(blank=True, null=True)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='justificaciones', to='core.Persona')),
            ],
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('estado', models.CharField(max_length=128)),
                ('justificacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Justificacion')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes', to='core.Persona')),
            ],
        ),
        migrations.AlterField(
            model_name='configuracion',
            name='tipo',
            field=models.IntegerField(choices=[(1, 'Numero'), (2, 'Cadena'), (3, 'JSON'), (4, 'Booleano'), (5, 'Hora'), (6, 'Fecha'), (7, 'Fecha Hora')]),
        ),
    ]
