# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 12:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20170213_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='horario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='personas', to='core.Horario'),
            preserve_default=False,
        ),
    ]
